import { User, Group, Expense } from "./types";

export const CURRENT_USER_ID = "user_me";

export const SEED_USERS: User[] = [
  {
    id: "user_me",
    name: "You",
    upiId: "you@okaxis",
    phone: "9999999999",
    color: "#1CC29F",
  },
  {
    id: "user_rahul",
    name: "Rahul",
    upiId: "rahul@okhdfcbank",
    phone: "9876543210",
    color: "#FF652F",
  },
  {
    id: "user_priya",
    name: "Priya",
    upiId: "priya@okicici",
    phone: "9123456780",
    color: "#7C3AED",
  },
  {
    id: "user_sara",
    name: "Sara",
    upiId: "sara@ybl",
    phone: "9988776655",
    color: "#DB2777",
  },
  {
    id: "user_aman",
    name: "Aman",
    upiId: "aman@paytm",
    phone: "9871234560",
    color: "#D97706",
  },
  {
    id: "user_kiran",
    name: "Kiran",
    upiId: "kiran@upi",
    phone: "9001234567",
    color: "#0891B2",
  },
  {
    id: "user_neha",
    name: "Neha",
    upiId: "neha@okaxis",
    phone: "9876001234",
    color: "#059669",
  },
  {
    id: "user_vikram",
    name: "Vikram",
    upiId: "vikram@okhdfcbank",
    phone: "9812345670",
    color: "#6366F1",
  },
];

export const SEED_GROUPS: Group[] = [
  {
    id: "group_goa",
    name: "Goa Trip",
    type: "trip",
    emoji: "🏖️",
    memberIds: ["user_me", "user_rahul", "user_priya", "user_sara"],
  },
  {
    id: "group_flat",
    name: "Flat 304",
    type: "flat",
    emoji: "🏠",
    memberIds: ["user_me", "user_rahul", "user_aman"],
  },
  {
    id: "group_lunch",
    name: "Office Lunch",
    type: "other",
    emoji: "🍱",
    memberIds: ["user_me", "user_kiran", "user_neha", "user_vikram", "user_sara"],
  },
];

// paise = rupees * 100
const r = (rupees: number) => Math.round(rupees * 100);

export const SEED_EXPENSES: Expense[] = [
  // ─── Goa Trip ───────────────────────────────────────────────────────
  {
    id: "exp_goa_villa",
    groupId: "group_goa",
    description: "Beach villa (2 nights)",
    amountPaise: r(8000),
    paidBy: { user_rahul: r(8000) },
    splitAmong: {
      user_me: r(2000),
      user_rahul: r(2000),
      user_priya: r(2000),
      user_sara: r(2000),
    },
    category: "accommodation",
    dateISO: "2024-12-28",
    createdVia: "manual",
  },
  {
    id: "exp_goa_cab1",
    groupId: "group_goa",
    description: "Cab from airport",
    amountPaise: r(960),
    paidBy: { user_me: r(960) },
    splitAmong: {
      user_me: r(240),
      user_rahul: r(240),
      user_priya: r(240),
      user_sara: r(240),
    },
    category: "transport",
    dateISO: "2024-12-27",
    createdVia: "manual",
  },
  {
    id: "exp_goa_dinner1",
    groupId: "group_goa",
    description: "Seafood dinner at Britto's",
    amountPaise: r(3200),
    paidBy: { user_priya: r(3200) },
    splitAmong: {
      user_me: r(800),
      user_rahul: r(800),
      user_priya: r(800),
      user_sara: r(800),
    },
    category: "food",
    dateISO: "2024-12-28",
    createdVia: "manual",
  },
  {
    id: "exp_goa_drinks",
    groupId: "group_goa",
    description: "Cocktails at Thalassa",
    amountPaise: r(2400),
    paidBy: { user_rahul: r(2400) },
    splitAmong: {
      user_me: r(600),
      user_rahul: r(900),
      user_priya: r(600),
      user_sara: r(300),
    },
    category: "food",
    dateISO: "2024-12-28",
    createdVia: "manual",
    notes: "Rahul had extra rounds, Sara had just one drink",
  },
  {
    id: "exp_goa_watersports",
    groupId: "group_goa",
    description: "Water sports (jet ski + banana boat)",
    amountPaise: r(2800),
    paidBy: { user_me: r(2800) },
    splitAmong: {
      user_me: r(700),
      user_rahul: r(700),
      user_priya: r(700),
      user_sara: r(700),
    },
    category: "activity",
    dateISO: "2024-12-29",
    createdVia: "manual",
  },
  {
    id: "exp_goa_groceries",
    groupId: "group_goa",
    description: "Groceries + breakfast stuff",
    amountPaise: r(1200),
    paidBy: { user_sara: r(1200) },
    splitAmong: {
      user_me: r(300),
      user_rahul: r(300),
      user_priya: r(300),
      user_sara: r(300),
    },
    category: "groceries",
    dateISO: "2024-12-29",
    createdVia: "manual",
  },
  {
    id: "exp_goa_cab2",
    groupId: "group_goa",
    description: "Cab to airport (return)",
    amountPaise: r(840),
    paidBy: { user_rahul: r(840) },
    splitAmong: {
      user_me: r(210),
      user_rahul: r(210),
      user_priya: r(210),
      user_sara: r(210),
    },
    category: "transport",
    dateISO: "2024-12-31",
    createdVia: "manual",
  },
  {
    id: "exp_goa_lunch",
    groupId: "group_goa",
    description: "Beach shack lunch",
    amountPaise: r(1600),
    paidBy: { user_priya: r(1600) },
    splitAmong: {
      user_me: r(400),
      user_rahul: r(400),
      user_priya: r(400),
      user_sara: r(400),
    },
    category: "food",
    dateISO: "2024-12-30",
    createdVia: "manual",
  },

  // ─── Flat 304 ────────────────────────────────────────────────────────
  {
    id: "exp_flat_rent_jan",
    groupId: "group_flat",
    description: "January rent",
    amountPaise: r(27000),
    paidBy: { user_me: r(27000) },
    splitAmong: {
      user_me: r(9000),
      user_rahul: r(9000),
      user_aman: r(9000),
    },
    category: "rent",
    dateISO: "2025-01-01",
    createdVia: "manual",
  },
  {
    id: "exp_flat_electricity",
    groupId: "group_flat",
    description: "Electricity bill (Dec)",
    amountPaise: r(1800),
    paidBy: { user_rahul: r(1800) },
    splitAmong: {
      user_me: r(600),
      user_rahul: r(600),
      user_aman: r(600),
    },
    category: "utilities",
    dateISO: "2025-01-05",
    createdVia: "manual",
  },
  {
    id: "exp_flat_groceries",
    groupId: "group_flat",
    description: "Weekly groceries",
    amountPaise: r(2400),
    paidBy: { user_aman: r(2400) },
    splitAmong: {
      user_me: r(800),
      user_rahul: r(800),
      user_aman: r(800),
    },
    category: "groceries",
    dateISO: "2025-01-08",
    createdVia: "manual",
  },
  {
    id: "exp_flat_wifi",
    groupId: "group_flat",
    description: "WiFi bill",
    amountPaise: r(1299),
    paidBy: { user_me: r(1299) },
    splitAmong: {
      user_me: r(433),
      user_rahul: r(433),
      user_aman: r(433),
    },
    category: "utilities",
    dateISO: "2025-01-10",
    createdVia: "manual",
  },

  // ─── Office Lunch ────────────────────────────────────────────────────
  {
    id: "exp_lunch_biryani",
    groupId: "group_lunch",
    description: "Biryani Friday",
    amountPaise: r(1250),
    paidBy: { user_me: r(1250) },
    splitAmong: {
      user_me: r(250),
      user_kiran: r(250),
      user_neha: r(250),
      user_vikram: r(250),
      user_sara: r(250),
    },
    category: "food",
    dateISO: "2025-01-10",
    createdVia: "manual",
  },
  {
    id: "exp_lunch_pizza",
    groupId: "group_lunch",
    description: "Pizza + garlic bread",
    amountPaise: r(960),
    paidBy: { user_kiran: r(960) },
    splitAmong: {
      user_me: r(192),
      user_kiran: r(192),
      user_neha: r(192),
      user_vikram: r(192),
      user_sara: r(192),
    },
    category: "food",
    dateISO: "2025-01-13",
    createdVia: "manual",
  },
  {
    id: "exp_lunch_thali",
    groupId: "group_lunch",
    description: "Thali + lassi",
    amountPaise: r(875),
    paidBy: { user_neha: r(875) },
    splitAmong: {
      user_me: r(175),
      user_kiran: r(175),
      user_neha: r(175),
      user_vikram: r(175),
      user_sara: r(175),
    },
    category: "food",
    dateISO: "2025-01-15",
    createdVia: "manual",
  },
];
